name: Deploy to GKE and Push to Artifact Registry

on:
  push:
    tags:
      - 'release*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure GCP environment
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker asia-south1-docker.pkg.dev

      # Obtain the short SHA-1 hash of the latest commit and echo the env var as SHA_SHORT, appending it to the file github_env
      - name: Set outputs
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Print build parameters
      - name: Print Build Parameters
        run: |
          echo "Build Parameters:"
          echo "  - Docker Image Tag: asia-south1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/linu-artifact-repo/python-app:${{ env.SHA_SHORT }}"
          echo "  - GitHub Ref: $GITHUB_REF"
          echo "  - Short SHA-1: ${{ env.SHA_SHORT }}"

      # Build the Docker image
      - name: Build
        run: |-
          docker build \
            --tag "asia-south1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/linu-artifact-repo/python-app:${{ env.SHA_SHORT }}" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      # Push the Docker image to Google Cloud Artifact Registry
      - name: Publish
        run: |-
          docker push "asia-south1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/linu-artifact-repo/python-app:${{ env.SHA_SHORT }}"

      - name: Set latest tag as output
        id: set-latest-tag
        run: echo "::set-output name=latest_tag::${{ env.SHA_SHORT }}"

      - name: Authenticate to GKE
        run: gcloud container clusters get-credentials gke-cluster --zone asia-south1-a --project river-blade-408018

      - name: Update Kubernetes Deployment
        run: |
          echo "Updating Kubernetes Deployment..."

          sed -i "s#asia-south1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/linu-artifact-repo/python-app:.*#asia-south1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/linu-artifact-repo/python-app:${{ env.SHA_SHORT }}#" .github/deploy/deployment.yaml
          kubectl apply -f .github/deploy/deployment.yaml -n linu-ns
          echo "Issuing rollout restart..."
          kubectl rollout restart deploy python-app -n linu-ns

      - name: Commit and Push Updated Deployment File
        run: |
          git add .github/deploy/deployment.yaml
          git -c user.email="linujose23@gmail.com" -c user.name="linujose23" \
              commit -m "Update Docker image tag in deployment.yaml [skip ci]"
          git push origin ${{ github.ref }} --quiet
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
